apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-hostname
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-hostname
  template:
    metadata:
      labels:
        app: echo-hostname
    spec:
      containers:
        - name: echo-hostname
          image: ireneminhee/echo-hostname:580222a3bd41f376fe7b834dc9abea0f935f5b43
          ports:
            - containerPort: 5000
